name: MSBuild
on:
  push:
    branches:
      - master
      - msbuild-test
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
  
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      
    - name: MSBuild
      run: dotnet build MahjongKeyboad.sln -p:OutDir="out/"
      shell: cmd
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-result
        path: ./out/
